# inventory.ini definiert die Hosts und Gruppen für Ansible 

# [wg_server]
# admin-vm ansible_host=192.168.114.50

[wg_server]
admin-vm ansible_connection=local ansible_host=192.168.114.50 # Testweise lokale Verbindung, da das Playbook auf der Admin-VM ausgeführt wird

[wg_clients] # vorerst nur platzhalter, da die Clients erst später hinzugefügt werden
vm1 ansible_host=192.168.114.51
vm2 ansible_host=192.168.114.52

[all:vars]
ansible_user=ms
ansible_python_interpreter=/usr/bin/python3