# inventory.ini definiert die Hosts und Gruppen für Ansible 

# [wg_server]
# admin-vm ansible_host=192.168.56.10

[wg_server]
admin-vm ansible_connection=local ansible_host=192.168.56.10 # Testweise lokale Verbindung, da das Playbook auf der Admin-VM ausgeführt wird

# vorerst nur platzhalter, da die Clients erst später hinzugefügt werden
[wg_clients]
vm1       ansible_host=192.168.56.20 ansible_user=IRGENDWAS wg_vpn_ip=10.8.0.2
# vm2       ansible_host=192.168.56.30 ansible_user=IRGENDWAS wg_vpn_ip=10.8.0.3
# Zukünftige VM ansible_host=192.168.56.X ansible_user=IRGENDWAS wg_vpn_ip=10.8.0.X

[all:vars]
ansible_python_interpreter=/usr/bin/python3
